### ISSUE TITLE
Evaluationsfeatures

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/quiz#25]
Von AR:

- [x] #28
- [x] die Zeitbegrenzung sollte für die Auswertung da raus, damit ich auch mit einigen Studierenden arbeiten kann, von denen manche vielleicht wieder einiges vergessen haben
- [x] eine Möglichkeit, aus einer von mir definierten Datei alle Fragen zu nehmen (wahrscheinlich ist das einfach nur ein Hochstellen der Fragenanzahl, bis die größer ist als die Anzahl der gegebenen Fragen, und das Ersetzen der Questiondata-Datei)

**Comment by KonradHoeffner** [comment]
Ich schreibe die Fragen lieber mit in die Tabelle, dann lässt sich das viel einfacher auswerten.

**Comment by KonradHoeffner** [comment]
Drei neue get parameter:

- 'count' ist die maximale Anzahl an Fragen. Auf 0 setzen für unlimitiert., 
- 'time' ist die Anzahl an Sekunden pro Frage. Auf 0 setzen für unlimitiert.
- 'deterministic' wenn vorhanden (Wert egal) führt dazu, dass die Fragen  nicht zufällig gezogen sondern vom Anfang an genommen werden und damit immer dieselben sind.

Für deine Zwecke brauchst du also `npm run dev` und dann `http://localhost:8080/?deterministic&time=0&count=0` oder wenn es dann deployed ist `https://www.snik.eu/quiz?deterministic&time=0&count=0`

**Comment by KonradHoeffner** [comment]
- [ ] Freitextfeld hinzufügen
Auf Wunsch der Evaluierer wird noch ein Freitextfeld pro Frage hinzugefügt um eine qualitative Evaluation zu ermöglichen, z.B. mit MAXQDA (Lizenz über Uni verfügbar).

**Comment by acklay4** [comment]
- [ ] Gerade ist es noch so, dass die Anzahl der Versuche leider nur die Reihenfolge der Fragen im Quiz, nicht in der quiz-data.jsx abbildet. Damit kann ich die Ergebnisse aber nicht den Fragen selbst zuordnen, da diese ja randomisiert angeordnet werden

**Comment by KonradHoeffner** [comment]
Was meinst du damit? Bei mir funktioniert das.
quiz-data.jsx erste 5 Fragen:

```js
{question: <span> What is defined by this? "Logical and chronological sequence of enterprise functions which interpret or update data about entities. Different from business processes, information processes do not contain the conditions under which enterprise functions are performed."</span>, answers: [<span> 3LGM² Information Process</span>,<span>entity type</span>,<span>software product</span>,<span>UML Class</span>,], correct: 0},
{question: <span> What is defined by this? "The X contains all clinical data about a patient, including medical and nursing anamnesis, finding discharge summery etc."</span>, answers: [<span> Patient History</span>,<span>Activity</span>,<span>Diagnosis</span>,<span>Finding</span>,], correct: 0},
{question: <span> What is defined by this? " diverse software products from different manufacturers lead to very heterogeneous (DB  n  , AC  n  , V  n  ) architectures. At the physical tool layer, heterogeneity is often the consequence of the evolution of the HIS, comprising different generations of computer systems."</span>, answers: [<span> Heterogeneous Architecture</span>,<span>HIS Architecture</span>,<span>Architecture of an Information System</span>,<span>Computer-Based Tool</span>,], correct: 0},
{question: <span> What is defined by this? "Change of the storage media during the transcription of data."</span>, answers: [<span> Media Crack</span>,<span>entity type</span>,<span>software product</span>,<span>Information Management Entity Type</span>,], correct: 0},
{question: <span> What is defined by this? "X typically comprises the introduction of the patient to the ward and nursing history and is done by the responsible nurse. For the nursing history there may be computer-based or department-specific, (semi-)standardized data entry forms available. These may contain information about the current diagnoses and therapy, orientation, mobility etc. The information should be available during the whole stay."</span>, answers: [<span> Nursing Admission</span>,<span>Bed</span>,<span>Case</span>,<span>Diagnosis</span>,], correct: 0},
```

Die 5 Fragen von <https://snik.eu/quiz?deterministic&count=5>

- What is defined by this? "Logical and chronological sequence of enterprise functions which interpret or update data about entities. Different from business processes, information processes do not contain the conditions under which enterprise functions are performed."
- What is defined by this? "The X contains all clinical data about a patient, including medical and nursing anamnesis, finding discharge summery etc."
-  What is defined by this? " diverse software products from different manufacturers lead to very heterogeneous (DB n , AC n , V n ) architectures. At the physical tool layer, heterogeneity is often the consequence of the evolution of the HIS, comprising different generations of computer systems."
- What is defined by this? "Change of the storage media during the transcription of data."
-  What is defined by this? "X typically comprises the introduction of the patient to the ward and nursing history and is done by the responsible nurse. For the nursing history there may be computer-based or department-specific, (semi-)standardized data entry forms available. These may contain information about the current diagnoses and therapy, orientation, mobility etc. The information should be available during the whole stay."

Das stimmt doch überein.

**Comment by KonradHoeffner** [comment]
Ist nun alles drin.
