### ISSUE TITLE
Clunky questions

### ISSUE THREAD

**Issue by Yeisoldt** [snikproject/quiz#7]
Try adding role/function/entity type to question in order to increase comprehensibility and improve overall sound of questions.

**Comment by KonradHoeffner** [comment]
While that would help comprehensibility, I think that would make it sound even more clunky.
For example, "Who is responsible for budget planning?" is both comprehensible and sounds natural, but "Who is responsible for the function of budget planning?" or "Who is responsible for budget planning (function)?" sounds less natural to me.
